export const BOT_UNIVERSES = [
  "GoT/HotD/KotSK",
  "CoD",
  "Marvel",
  "DC",
  "Invincible",
  "The Boys",
  "The Immortals",
  "Lord of the Rings",
  "Dune",
  "Boardwalk Empire",
  "Ripper Street",
  "Bridgerton",
  "Ghosts (BBC)",
  "Breaking Bad",
  "Better Call Saul",
  "The Sopranos",
  "The Wire",
  "Stranger Things",
  "The X-Files",
  "Doctor Who",
  "The Walking Dead",
  "Supernatural",
  "Peaky Blinders",
  "Penny Dreadful",
  "Sherlock Holmes",
  "The Hunger Games",
  "The Maze Runner",
  "Narnia",
  "His Dark Materials",
  "Foundation",
  "The Matrix",
  "Halo (Game series)",
  "Resident Evil",
  "The Conjuring",
  "Studio Ghibli",
  "Stephen King",
  "Jurassic Park",
  "Planet of the Apes",
  "Avatar: The Last Airbender",
  "Arcane/League of Legends",
  "MonsterVerse (Godzilla/Kong)",
  "Alien",
  "Terminator",
  "Blade Runner",
  "James Bond",
  "John Wick",
  "Mission: Impossible",
  "Indiana Jones",
  "Pirates of the Caribbean",
  "Avatar (James Cameron)",
  "Greek mythology",
  "Norse mythology",
  "Egyptian mythology",
  "Roman mythology",
  "Celtic mythology",
  "Japanese mythology",
  "Hindu mythology",
  "Slavic mythology",
  "Historical figures",
  "DragonBall",
  "TTRPG",
  "Naruto",
  "One Piece",
  "Attack on Titan",
  "Jujutsu Kaisen",
  "Assassin's Creed",
  "The Witcher",
  "dishonored",
  "cyberpunk",
  "Castlevania",
  "Elden Ring",
  "The Elder Scrolls",
  "Mass Effect",
  "Final Fantasy",
  "MTG",
  "Sailor moon",
  "Masters of the Universe",
  "Starwars",
  "Startrek",
  "Sinners",
  "Twilight",
  "Fallout",
  "OC (Original Character)",
] as const

export type BotUniverse = (typeof BOT_UNIVERSES)[number]