export const UNIVERSE_CATEGORIES = {
  "Anime & Animation": [
    "Attack on Titan",
    "Avatar: The Last Airbender",
    "DragonBall",
    "Jujutsu Kaisen",
    "Naruto",
    "One Piece",
    "Sailor moon",
    "Studio Ghibli",
  ],
  "Crime, Action & Drama": [
    "Better Call Saul",
    "Boardwalk Empire",
    "Breaking Bad",
    "Bridgerton",
    "Indiana Jones",
    "James Bond",
    "John Wick",
    "Mission: Impossible",
    "Peaky Blinders",
    "Ripper Street",
    "Sherlock Holmes",
    "The Sopranos",
    "The Wire",
  ],
  "Fantasy & Magic": [
    "GoT/HotD/KotSK",
    "His Dark Materials",
    "Lord of the Rings",
    "Masters of the Universe",
    "Narnia",
    "Pirates of the Caribbean",
    "The Immortals",
    "Twilight",
  ],
  "Horror & Supernatural": [
    "Ghosts (BBC)",
    "Penny Dreadful",
    "Stephen King",
    "Supernatural",
    "The Conjuring",
    "The Walking Dead",
  ],
  "Mythology & History": [
    "Celtic mythology",
    "Egyptian mythology",
    "Greek mythology",
    "Hindu mythology",
    "Historical figures",
    "Japanese mythology",
    "Norse mythology",
    "Roman mythology",
    "Slavic mythology",
  ],
  "Sci-Fi & Dystopian": [
    "Alien",
    "Avatar (James Cameron)",
    "Blade Runner",
    "Doctor Who",
    "Dune",
    "Foundation",
    "Jurassic Park",
    "MonsterVerse (Godzilla/Kong)",
    "Planet of the Apes",
    "Startrek",
    "Starwars",
    "Stranger Things",
    "Terminator",
    "The Hunger Games",
    "The Matrix",
    "The Maze Runner",
    "The X-Files",
  ],
  "Superheroes & Comics": [
    "DC",
    "Invincible",
    "Marvel",
    "The Boys",
  ],
  "Video Games & Tabletop": [
    "Arcane/League of Legends",
    "Assassin's Creed",
    "Castlevania",
    "CoD",
    "cyberpunk",
    "dishonored",
    "Elden Ring",
    "Fallout",
    "Final Fantasy",
    "Halo (Game series)",
    "Mass Effect",
    "MTG",
    "Resident Evil",
    "TTRPG",
    "The Elder Scrolls",
    "The Witcher",
  ],
  "General / Original": [
    "OC (Original Character)",
    "Sinners",
  ],
} as const;

// We flatten the object back into your original array so we don't break any 
// existing backend code or database validations that rely on BOT_UNIVERSES!
export const BOT_UNIVERSES = Object.values(UNIVERSE_CATEGORIES).flat();

export type BotUniverse = (typeof BOT_UNIVERSES)[number];