export const BOT_UNIVERSES = [
  "GoT/HotD/KotSK",
  "CoD",
  "Marvel",
  "DC",
  "Invincible",
  "The Boys",
  "The Immortals",
  "Lord of the Rings",
  "Dune",
  "Peaky Blinders",
  "Penny Dreadful",
  "Historical figures",
  "DragonBall",
  "TTRPG",
  "Naruto",
  "One Piece",
  "Attack on Titan",
  "Jujutsu Kaisen",
  "Assassin's Creed",
  "The Witcher",
  "dishonored",
  "cyberpunk",
  "Castlevania",
  "Elden Ring",
  "The Elder Scrolls",
  "Mass Effect",
  "Final Fantasy",
  "Starwars",
  "Startrek",
  "Sinners",
  "Twilight",
  "Fallout",
  "OC (Original Character)",
] as const

export type BotUniverse = (typeof BOT_UNIVERSES)[number]